### ISSUE TITLE
Docker環境の作成

### ISSUE THREAD

**Issue by arihh** [medpeer-inc/kaonajimi#1]

**Comment by kyo-nanba** [comment]
とりあえず `rails` とは独立してDocker環境だけを作り始めたのですが、 `rails` が無いと `entrypoint.sh` の内容とか `docker-compose.yml` に書く内容が意味不明な感じになってしまうので `rails new` してしまおうと思います。

**Comment by kyo-nanba** [comment]
Slack連携テスト

**Comment by kyo-nanba** [comment]
Slack連携テスト2

**Comment by kyo-nanba** [comment]
自分の権限チェックテスト
